require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Lint/DuplicateBranch:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false