require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 155

Lint/DuplicateBranch:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/ActionControllerFlashBeforeRender:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
  Exclude:
    - 'app/controllers/users/**/*'

Rails/BulkChangeTable:
  Enabled: false
  Exclude:
    - 'app/migrate/**/*'

Rails/SkipsModelValidations:
  Enabled: false
  Exclude:
    - 'app/migrate/**/*'